### ISSUE TITLE
[Schedule] one-time tasks

### ISSUE THREAD

**Issue by TyranicMoron** [TyranicMoron/PyMoronBot#188]
Replace the Delay module.
Library used in Time module could be relevant.

- [ ] schedule with a time (schedule time 00:00 taskname command params)
- [ ] schedule with a date (schedule date 2018-02-16 00:00 taskname command params)
- [ ] schedule with a duration (schedule timer 3h5m taskname command params)
- [ ] if activation time has passed at time of loading, activate immediately
- [ ] deletes itself after execution

**Comment by StarlitGhost** [comment]
This issue was moved to DesertBot/DesertBot#9
