### ISSUE TITLE
Trigger command, for setting up regex triggers like URLFollow and Responses

### ISSUE THREAD

**Issue by TyranicMoron** [TyranicMoron/PyMoronBot#99]
Syntax:

Add a trigger:
`.trigger add triggerName "regex" command`
Some prefixes before the regex could specify what part of the message it looks at, eg `n"regex"` for nick. It would default to the text.

Delete a trigger:
`.trigger del triggerName`
List all triggers (just names):
`.trigger list`
Show the contents of a trigger:
`.trigger show triggerName`
Export triggers to paste.ee in `.trigger add` format:
`.trigger export triggerName/all`
Import triggers from paste.ee:
`.trigger import <paste.ee address>`

**Comment by StarlitGhost** [comment]
This issue was moved to DesertBot/DesertBot#5
